const std = @import("std");

const Sha256 = std.crypto.hash.sha2.Sha256;

pub const digest_bytes = 32;
pub const digest_hex_bytes = digest_bytes * 2;

/// The default workload is the smallest admission-sized editor fixture.  The
/// generated bytes live in the build cache; this source file is the fixture.
pub const minimum_output_bytes: usize = 10 * 1024 * 1024;
pub const maximum_target_bytes: usize = 11 * 1024 * 1024;
pub const maximum_output_bytes: usize = 12 * 1024 * 1024;
pub const default_seed: u64 = 0x5445_5846_4c4f_5732;

const line_capacity = 8192;
const output_reserve_headroom = 64 * 1024;
const maximum_sections: u64 = 512;
const sections_per_chapter: u64 = 8;
const paragraphs_per_section: u64 = 8;
const body_lines_per_paragraph: u64 = 12;

const line_hash_domain = "texflow:t0.2d:fixture-lines:v1\x00";
const section_hash_domain = "texflow:t0.2d:fixture-sections:v1\x00";

pub const Options = struct {
    target_bytes: usize = minimum_output_bytes,
    seed: u64 = default_seed,
};

pub const Metrics = struct {
    byte_count: u64 = 0,
    line_count: u64 = 0,
    section_count: u64 = 0,
    chapter_count: u64 = 0,
    paragraph_count: u64 = 0,
    /// Generated command sites; lexical commands embedded in prose are not
    /// counted twice by a second source scan.
    command_count: u64 = 0,
    comment_line_count: u64 = 0,
    math_block_count: u64 = 0,
    inline_math_count: u64 = 0,
    table_count: u64 = 0,
    citation_count: u64 = 0,
    reference_count: u64 = 0,
    label_count: u64 = 0,
    nfc_count: u64 = 0,
    decomposed_count: u64 = 0,
    cjk_count: u64 = 0,
    bidi_count: u64 = 0,
    emoji_count: u64 = 0,
    long_line_count: u64 = 0,
    crlf_line_count: u64 = 0,
    lf_line_count: u64 = 0,
    cr_line_count: u64 = 0,
    max_line_bytes: u64 = 0,
    byte_sha256: [digest_bytes]u8 = [_]u8{0} ** digest_bytes,
    line_sha256: [digest_bytes]u8 = [_]u8{0} ** digest_bytes,
    section_sha256: [digest_bytes]u8 = [_]u8{0} ** digest_bytes,

    pub fn byteHashHex(self: Metrics) [digest_hex_bytes]u8 {
        return std.fmt.bytesToHex(self.byte_sha256, .lower);
    }

    pub fn lineHashHex(self: Metrics) [digest_hex_bytes]u8 {
        return std.fmt.bytesToHex(self.line_sha256, .lower);
    }

    pub fn sectionHashHex(self: Metrics) [digest_hex_bytes]u8 {
        return std.fmt.bytesToHex(self.section_sha256, .lower);
    }
};

pub const Book = struct {
    allocator: std.mem.Allocator,
    bytes: []u8,
    metrics: Metrics,

    pub fn deinit(self: *Book) void {
        self.allocator.free(self.bytes);
        self.* = undefined;
    }
};

pub const GeneratedBook = Book;

const Line = struct {
    bytes: [line_capacity]u8 = undefined,
    len: usize = 0,

    fn append(self: *Line, value: []const u8) !void {
        if (value.len > line_capacity - self.len) return error.LineTooLong;
        @memcpy(self.bytes[self.len .. self.len + value.len], value);
        self.len += value.len;
    }

    fn print(self: *Line, comptime format: []const u8, args: anytype) !void {
        var scratch: [256]u8 = undefined;
        const rendered = std.fmt.bufPrint(&scratch, format, args) catch return error.LineTooLong;
        try self.append(rendered);
    }

    fn slice(self: *const Line) []const u8 {
        return self.bytes[0..self.len];
    }
};

const Builder = struct {
    allocator: std.mem.Allocator,
    seed: u64,
    output: std.ArrayList(u8) = .empty,
    metrics: Metrics = .{},
    byte_hasher: Sha256 = Sha256.init(.{}),
    line_hasher: Sha256 = Sha256.init(.{}),
    section_records_hasher: Sha256 = Sha256.init(.{}),
    section_hasher: Sha256 = Sha256.init(.{}),
    in_section: bool = false,
    section_index: u64 = 0,
    section_bytes: u64 = 0,

    fn init(allocator: std.mem.Allocator, seed: u64) Builder {
        var builder = Builder{ .allocator = allocator, .seed = seed };
        builder.line_hasher.update(line_hash_domain);
        builder.section_records_hasher.update(section_hash_domain);
        return builder;
    }

    fn deinit(self: *Builder) void {
        self.output.deinit(self.allocator);
    }

    fn append(self: *Builder, value: []const u8) !void {
        if (value.len > maximum_output_bytes - self.output.items.len) {
            return error.OutputLimitExceeded;
        }
        try self.output.appendSlice(self.allocator, value);
        self.byte_hasher.update(value);
        if (self.in_section) {
            self.section_hasher.update(value);
            self.section_bytes += @intCast(value.len);
        }
    }

    fn line(self: *Builder, body: []const u8) !void {
        if (std.mem.indexOfAny(u8, body, "\r\n") != null) return error.LineContainsTerminator;

        const ending = lineEnding(self.metrics.line_count, self.seed);
        const remaining = maximum_output_bytes - self.output.items.len;
        if (ending.len > remaining or body.len > remaining - ending.len) {
            return error.OutputLimitExceeded;
        }
        try self.append(body);
        try self.append(ending);

        var index_bytes: [8]u8 = undefined;
        var length_bytes: [8]u8 = undefined;
        std.mem.writeInt(u64, &index_bytes, self.metrics.line_count, .little);
        std.mem.writeInt(u64, &length_bytes, @intCast(body.len), .little);
        self.line_hasher.update(&index_bytes);
        self.line_hasher.update(&length_bytes);
        self.line_hasher.update(body);

        var ending_tag = [1]u8{if (ending.len == 2) 2 else if (ending[0] == '\n') 1 else 3};
        self.line_hasher.update(&ending_tag);

        self.metrics.line_count += 1;
        self.metrics.max_line_bytes = @max(self.metrics.max_line_bytes, @as(u64, @intCast(body.len)));
        if (ending.len == 2) {
            self.metrics.crlf_line_count += 1;
        } else if (ending[0] == '\n') {
            self.metrics.lf_line_count += 1;
        } else {
            self.metrics.cr_line_count += 1;
        }
    }

    fn comment(self: *Builder, body: []const u8) !void {
        self.metrics.comment_line_count += 1;
        try self.line(body);
    }

    fn markCommand(self: *Builder, count: u64) void {
        self.metrics.command_count += count;
    }

    fn beginSection(self: *Builder, index: u64) !void {
        if (self.in_section) return error.UnbalancedSection;
        self.in_section = true;
        self.section_index = index;
        self.section_bytes = 0;
        self.section_hasher = Sha256.init(.{});
        self.section_hasher.update(section_hash_domain);

        var index_bytes: [8]u8 = undefined;
        std.mem.writeInt(u64, &index_bytes, index, .little);
        self.section_hasher.update(&index_bytes);
    }

    fn endSection(self: *Builder) !void {
        if (!self.in_section) return error.UnbalancedSection;

        var digest: [digest_bytes]u8 = undefined;
        self.section_hasher.final(&digest);

        var index_bytes: [8]u8 = undefined;
        var length_bytes: [8]u8 = undefined;
        std.mem.writeInt(u64, &index_bytes, self.section_index, .little);
        std.mem.writeInt(u64, &length_bytes, self.section_bytes, .little);
        self.section_records_hasher.update(&index_bytes);
        self.section_records_hasher.update(&length_bytes);
        self.section_records_hasher.update(&digest);

        self.metrics.section_count += 1;
        self.in_section = false;
    }

    fn finish(self: *Builder) !Metrics {
        if (self.in_section) return error.UnbalancedSection;
        var result = self.metrics;
        result.byte_count = @intCast(self.output.items.len);
        self.byte_hasher.final(&result.byte_sha256);
        self.line_hasher.final(&result.line_sha256);
        self.section_records_hasher.final(&result.section_sha256);
        return result;
    }
};

const chapter_topics = [_][]const u8{
    "Source Preservation",
    "Unicode Boundaries",
    "Accessible Structure",
    "Incremental State",
    "Visual Semantics",
    "Searchable Evidence",
    "Failure Recovery",
    "Measured Convergence",
};

const section_topics = [_][]const u8{
    "Inputs and invariants",
    "Canonical-equivalent text",
    "Logical and visual order",
    "Bounded updates",
    "Rendered evidence",
    "Cross-reference stability",
    "Adversarial boundaries",
    "Replayable observations",
};

const citation_keys = [_][]const u8{
    "ref:unicode",
    "ref:uia",
    "ref:scintilla",
    "ref:latex",
    "ref:measurement",
    "ref:accessibility",
};

const variants = [_][]const u8{
    "A bounded source record preserves its original byte sequence while derived views remain explicit.",
    "The editor model separates logical offsets, visual layout, and broker-owned evidence.",
    "A small deterministic state transition is easier to replay than an implicit repair.",
    "Every repeated observation carries an index so a long document stays inspectable.",
};

const vietnamese_nfc = "Tiếng Việt giữ nguyên dấu: đám mây, học tập, ngôn ngữ.";
const vietnamese_decomposed = "Tie\u{0302}\u{0301}ng Vie\u{0323}\u{0302}t giu\u{0303} nguye\u{0302}n da\u{0301}u.";
const cjk_text = "中文研究与日本語の節は同じソース順序に保たれる。漢字の境界も記録する。";
const bidi_text = "العربية تُحفظ بترتيب منطقي، וְעִבְרִית נשמרת ללא إعادة كتابة.";
const emoji_text = "🧪 🔬 🧠 🧭 🚀 ✨";
const long_line_fragment = " token-preserving-layout[alpha=7,beta=11] -> grapheme/word/line/page evidence;";

fn mix(seed: u64, value: u64) u64 {
    var z = seed ^ (value *% 0x9e37_79b9_7f4a_7c15);
    z = (z ^ (z >> 30)) *% 0xbf58_476d_1ce4_e5b9;
    z = (z ^ (z >> 27)) *% 0x94d0_49bb_1331_11eb;
    return z ^ (z >> 31);
}

fn lineEnding(line_index: u64, seed: u64) []const u8 {
    return switch ((line_index +% seed) % 3) {
        0 => "\r\n",
        1 => "\n",
        else => "\r",
    };
}

fn indexedLine(builder: *Builder, prefix: []const u8, index: u64, suffix: []const u8) !void {
    var line: Line = .{};
    try line.append(prefix);
    try line.print("{d}", .{index});
    try line.append(suffix);
    try builder.line(line.slice());
}

fn labelLine(builder: *Builder, prefix: []const u8, index: u64) !void {
    try indexedLine(builder, prefix, index, "}");
    builder.metrics.label_count += 1;
    builder.markCommand(1);
}

fn emitPreamble(builder: *Builder) !void {
    try builder.comment("% T0.2d deterministic fixture; source structure is not compiler proof.");
    try builder.line("\\documentclass[11pt,oneside]{book}");
    try builder.line("\\usepackage[utf8]{inputenc}");
    try builder.line("\\usepackage[T1]{fontenc}");
    try builder.line("\\usepackage{amsmath,amssymb,booktabs,hyperref}");
    try builder.line("\\newcommand{\\fixtureid}[1]{\\texttt{#1}}");
    try builder.line("\\begin{document}");
    try builder.line("\\title{TExFlow deterministic editor workload}");
    try builder.line("\\author{T0.2d fixture generator}");
    try builder.line("\\maketitle");
    try builder.line("\\tableofcontents");
    try builder.line("\\mainmatter");
    try builder.line("\\setcounter{secnumdepth}{3}");
    builder.markCommand(12);
}

fn emitParagraph(builder: *Builder, section_index: u64, paragraph_index: u64) !void {
    var heading: Line = .{};
    try heading.append("\\paragraph{Indexed observation ");
    try heading.print("{d}", .{paragraph_index});
    try heading.append("}");
    try builder.line(heading.slice());
    builder.markCommand(1);
    builder.metrics.paragraph_count += 1;

    var label_prefix: Line = .{};
    try label_prefix.append("\\label{para:");
    try label_prefix.print("{d}", .{paragraph_index});
    try labelLine(builder, label_prefix.slice(), paragraph_index);

    const line_count = body_lines_per_paragraph + (mix(builder.seed, paragraph_index) % 4);
    var body_index: u64 = 0;
    while (body_index < line_count) : (body_index += 1) {
        var line: Line = .{};
        try line.append("Paragraph ");
        try line.print("{d}", .{paragraph_index});
        try line.append(" line ");
        try line.print("{d}", .{body_index});
        try line.append(" repeats a stable semantic payload: ");
        try line.append(variants[@as(usize, @intCast((paragraph_index + body_index) % variants.len))]);

        switch ((paragraph_index + body_index) % 7) {
            0 => {
                try line.append(" ");
                try line.append(vietnamese_nfc);
                builder.metrics.nfc_count += 1;
            },
            1 => {
                try line.append(" ");
                try line.append(vietnamese_decomposed);
                builder.metrics.decomposed_count += 1;
            },
            2 => {
                try line.append(" ");
                try line.append(cjk_text);
                builder.metrics.cjk_count += 1;
            },
            3 => {
                try line.append(" ");
                try line.append(bidi_text);
                builder.metrics.bidi_count += 1;
            },
            4 => {
                try line.append(" ");
                try line.append(emoji_text);
                builder.metrics.emoji_count += 1;
            },
            5 => try line.append(" Escaped punctuation remains literal: 50\\% and {braces}."),
            else => try line.append(" Tabs\tand spaces remain observable source bytes."),
        }

        if (body_index % 2 == 0) {
            try line.append(" \\textbf{source-preserving}");
        } else {
            try line.append(" \\emph{derived-view-only}");
        }
        builder.markCommand(1);

        if (body_index % 3 == 0) {
            try line.append(" Inline $a_{");
            try line.print("{d}", .{paragraph_index});
            try line.append("} + b_{");
            try line.print("{d}", .{body_index});
            try line.append("} = c^2$");
            builder.metrics.inline_math_count += 1;
            builder.markCommand(1);
        }

        try line.append(" \\cite{");
        try line.append(citation_keys[@as(usize, @intCast((paragraph_index + body_index) % citation_keys.len))]);
        try line.append("} \\ref{sec:");
        try line.print("{d}", .{section_index});
        try line.append("}.");
        builder.metrics.citation_count += 1;
        builder.metrics.reference_count += 1;
        builder.markCommand(2);
        try builder.line(line.slice());
    }
}

fn emitMath(builder: *Builder, section_index: u64) !void {
    try builder.line("\\begin{equation}");
    var equation: Line = .{};
    try equation.append("\\mathcal{E}_{");
    try equation.print("{d}", .{section_index});
    try equation.append("} = \\sum_{i=0}^{n} x_i^2 + \\frac{\\alpha}{\\beta} + \\Delta");
    try builder.line(equation.slice());
    var label_prefix: Line = .{};
    try label_prefix.append("\\label{eq:");
    try labelLine(builder, label_prefix.slice(), section_index);
    try builder.line("\\end{equation}");
    builder.metrics.math_block_count += 1;
    builder.markCommand(3);
}

fn emitTable(builder: *Builder, section_index: u64) !void {
    try builder.line("\\begin{table}[htbp]");
    try builder.line("\\centering");
    try builder.line("\\begin{tabular}{lrr}");
    try builder.line("\\toprule");
    try builder.line("Unit & Bytes & UTF--16 \\\\");
    try builder.line("\\midrule");
    try builder.line("grapheme & 17 & 9 \\\\");
    try builder.line("word & 23 & 14 \\\\");
    var row: Line = .{};
    try row.append("section-");
    try row.print("{d}", .{section_index});
    try row.append(" & ");
    try row.print("{d}", .{section_index *% 97 + 31});
    try row.append(" & ");
    try row.print("{d}", .{section_index *% 53 + 17});
    try row.append(" \\\\");
    try builder.line(row.slice());
    try builder.line("\\bottomrule");
    try builder.line("\\end{tabular}");
    var caption: Line = .{};
    try caption.append("\\caption{Offset evidence for section ");
    try caption.print("{d}", .{section_index});
    try caption.append("}");
    try builder.line(caption.slice());
    builder.markCommand(1);
    var label_prefix: Line = .{};
    try label_prefix.append("\\label{tab:");
    try labelLine(builder, label_prefix.slice(), section_index);
    try builder.line("\\end{table}");
    builder.metrics.table_count += 1;
    builder.markCommand(11);
}

fn emitList(builder: *Builder, section_index: u64) !void {
    try builder.line("\\begin{itemize}");
    try builder.line("\\item source bytes stay lossless;");
    var item: Line = .{};
    try item.append("\\item section index ");
    try item.print("{d}", .{section_index});
    try item.append(" is stable across replays;");
    try builder.line(item.slice());
    try builder.line("\\item derived hashes are bounded and reproducible.");
    try builder.line("\\end{itemize}");
    builder.markCommand(5);
}

fn emitLongLine(builder: *Builder, section_index: u64) !void {
    var line: Line = .{};
    try line.append("long-line-checkpoint-");
    try line.print("{d}", .{section_index});
    try line.append(": ");
    const target = 4096 + @as(usize, @intCast(mix(builder.seed, section_index) % 1024));
    var fragment_index: usize = 0;
    while (line.len < target) : (fragment_index += 1) {
        try line.append(long_line_fragment);
        if (fragment_index > line_capacity / long_line_fragment.len) return error.LineTooLong;
    }
    try builder.line(line.slice());
    builder.metrics.long_line_count += 1;
}

fn emitSection(builder: *Builder, section_index: u64) !void {
    try builder.beginSection(section_index);

    const chapter_index = section_index / sections_per_chapter;
    if (section_index % sections_per_chapter == 0) {
        var chapter: Line = .{};
        try chapter.append("\\chapter{");
        try chapter.append(chapter_topics[@as(usize, @intCast(chapter_index % chapter_topics.len))]);
        try chapter.append(" ");
        try chapter.print("{d}", .{chapter_index + 1});
        try chapter.append("}");
        try builder.line(chapter.slice());
        builder.metrics.chapter_count += 1;
        builder.markCommand(1);

        var chapter_label: Line = .{};
        try chapter_label.append("\\label{chap:");
        try labelLine(builder, chapter_label.slice(), chapter_index + 1);
    }

    var section: Line = .{};
    try section.append("\\section{");
    try section.append(section_topics[@as(usize, @intCast(section_index % section_topics.len))]);
    try section.append(" ");
    try section.print("{d}", .{section_index});
    try section.append("}");
    try builder.line(section.slice());
    builder.markCommand(1);

    var section_label: Line = .{};
    try section_label.append("\\label{sec:");
    try labelLine(builder, section_label.slice(), section_index);
    try builder.comment("% Stable section boundary: all nested environments close before the next section.");

    var paragraph_index: u64 = section_index * paragraphs_per_section;
    var paragraph_offset: u64 = 0;
    while (paragraph_offset < paragraphs_per_section) : ({
        paragraph_offset += 1;
        paragraph_index += 1;
    }) {
        try emitParagraph(builder, section_index, paragraph_index);
    }

    try emitMath(builder, section_index);
    try emitTable(builder, section_index);
    try emitList(builder, section_index);
    try emitLongLine(builder, section_index);

    var cross_reference: Line = .{};
    try cross_reference.append("See Section \\ref{sec:");
    try cross_reference.print("{d}", .{section_index});
    try cross_reference.append("} and page \\pageref{sec:");
    try cross_reference.print("{d}", .{section_index});
    try cross_reference.append("} for the replay record.");
    try builder.line(cross_reference.slice());
    builder.metrics.reference_count += 2;
    builder.markCommand(2);

    try builder.endSection();
}

fn emitBibliography(builder: *Builder) !void {
    try builder.comment("% The bibliography closes every citation key used by the workload.");
    try builder.line("\\begin{thebibliography}{99}");
    for (citation_keys) |key| {
        var entry: Line = .{};
        try entry.append("\\bibitem{");
        try entry.append(key);
        try entry.append("} Deterministic reference for ");
        try entry.append(key);
        try entry.append(".");
        try builder.line(entry.slice());
    }
    try builder.line("\\end{thebibliography}");
    try builder.line("\\backmatter");
    try builder.line("\\end{document}");
    builder.markCommand(10);
}

fn validateOptions(options: Options) !void {
    if (options.target_bytes == 0 or options.target_bytes > maximum_target_bytes) {
        return error.InvalidTargetBytes;
    }
}

pub fn validateMetrics(metrics: Metrics, options: Options) !void {
    try validateOptions(options);
    if (metrics.byte_count < options.target_bytes or metrics.byte_count > maximum_output_bytes) {
        return error.InvalidGeneratedMetrics;
    }
    if (metrics.line_count == 0 or metrics.section_count == 0 or metrics.chapter_count == 0 or
        metrics.paragraph_count == 0 or metrics.command_count == 0 or metrics.math_block_count == 0 or
        metrics.inline_math_count == 0 or metrics.max_line_bytes < 4096 or
        metrics.crlf_line_count == 0 or metrics.lf_line_count == 0 or metrics.cr_line_count == 0 or
        metrics.nfc_count == 0 or metrics.decomposed_count == 0 or metrics.cjk_count == 0 or
        metrics.bidi_count == 0 or metrics.emoji_count == 0 or metrics.long_line_count == 0)
    {
        return error.InvalidGeneratedMetrics;
    }
}

pub fn generate(allocator: std.mem.Allocator, options: Options) !Book {
    try validateOptions(options);

    var builder = Builder.init(allocator, options.seed);
    errdefer builder.deinit();
    const reserve = @min(maximum_output_bytes, options.target_bytes + output_reserve_headroom);
    try builder.output.ensureTotalCapacity(allocator, reserve);

    try emitPreamble(&builder);
    var section_index: u64 = 0;
    while (builder.output.items.len < options.target_bytes) : (section_index += 1) {
        if (section_index >= maximum_sections) return error.SectionLimitExceeded;
        try emitSection(&builder, section_index);
    }
    try emitBibliography(&builder);

    const metrics = try builder.finish();
    try validateMetrics(metrics, options);
    return .{
        .allocator = allocator,
        .bytes = try builder.output.toOwnedSlice(allocator),
        .metrics = metrics,
    };
}

pub fn emit(allocator: std.mem.Allocator, options: Options) !Book {
    return generate(allocator, options);
}
